# Generated by Django 5.1 on 2024-09-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_recipe_carbohydrates_per_100g'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='calories_per_100g',
            new_name='carbohydrates',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='protein_per_100g',
            new_name='protein',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='carbohydrates_per_100g',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
