# Generated by Django 5.1 on 2024-09-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_recipe_instructions_remove_recipe_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='process',
            field=models.TextField(default='No process provided'),
        ),
    ]
