# Generated by Django 5.1 on 2024-08-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DOB',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Weightloss', 'Weightloss'), ('Weightgain', 'Weightgain'), ('Get-fit', 'Getfit'), ('Lifestyle', 'Lifestyle'), ('Recovery', 'Recovery')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
