# Generated by Django 5.1 on 2024-09-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_recipe_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein_per_100g',
            field=models.FloatField(default=0.0),
        ),
    ]
