# Generated by Django 5.1 on 2024-10-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0017_remove_question_option_a_remove_question_option_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
