# Generated by Django 5.1 on 2024-10-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0019_alter_event_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
